# Generated by Django 4.2.7 on 2023-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('1', 'Manzel'), ('2', 'Aparteman'), ('3', 'Zamin&Kolangi'), ('4', 'Baf&arazi'), ('5', 'Tejari'), ('6', 'Saanati'), ('7', 'Edari'), ('8', 'Tehatar'), ('9', 'EjareRuzane'), ('10', 'PishForosh')], max_length=50)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
