# Generated by Django 4.2.7 on 2023-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
